# Generated by Django 5.1.2 on 2024-11-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_address',
            field=models.CharField(blank=True, default='0x00', max_length=42),
        ),
    ]
