# Generated by Django 5.1.2 on 2024-11-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_profile_social_score_profile_wallet_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
