# Generated by Django 5.1.2 on 2024-11-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_delete_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
