# Generated by Django 5.1.2 on 2024-11-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_profile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pfp.jpg', upload_to='profile_pics'),
        ),
    ]
