# Generated by Django 5.1.1 on 2024-10-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_user_id', models.CharField(max_length=50)),
                ('twitter_username', models.CharField(default='newUser', max_length=15)),
                ('token_type', models.CharField(max_length=10)),
                ('expires_in', models.IntegerField()),
                ('access_token', models.CharField(max_length=150)),
                ('scope', models.CharField(max_length=150)),
                ('refresh_token', models.CharField(max_length=150)),
                ('expires_at', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='new_access_token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
            },
        ),
    ]
