# Generated by Django 5.1.2 on 2024-11-09 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_post_updated_at_bookmark_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
